# Generated by Django 5.1.4 on 2024-12-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_palette_app', '0002_colorpalette'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='colorpalette',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
