# Generated by Django 5.1.4 on 2024-12-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_palette_app', '0003_rename_uploaded_at_imageupload_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalette',
            name='rgb_codes',
            field=models.TextField(blank=True),
        ),
    ]
