# Generated by Django 5.1.4 on 2024-12-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_palette_app', '0004_colorpalette_rgb_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalette',
            name='k_value',
            field=models.IntegerField(default=5),
        ),
    ]
