# Generated by Django 3.1.2 on 2024-12-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_palette_app', '0005_colorpalette_k_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
